### PR TITLE
Add invalidates facts

### PR DESCRIPTION
**Pull request by spastorino**
I'll leave this here as a discussion starting point :).

Related to #4

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Can you add that to the list of things to add here

https://github.com/rust-lang-nursery/borrow-check/blob/4945c130cb1f3af7c072dc9856b6fe21b3a9f1f7/src/tab_delim.rs#L33-L42

probably we will need to `touch` the various files as a result

**Comment by spastorino** [comment]
@nikomatsakis unsure what's going on, but I have added that and see when I click on commit. Unsure why you don't see the change.

**Comment by nikomatsakis** [comment]
oh, I must be blind. I see it now =)

**Comment by spastorino** [comment]
This can be closed, is superseded by https://github.com/rust-lang-nursery/polonius/pull/34

**Pull request closed without merging**
